name: Tidyverse Korea
on: push

jobs:
  my-job:
    name: Korean Test
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: 제 이름은 다음과 같습니다.
        FIRST_NAME: Tidyverse
        LAST_NAME: Korea
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
