name: Render Weather Report

# Controls when the action will run
on:
  push:
    branches: gh-pages

jobs:
  render:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    # install packages needed
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "httr", "glue", "jsonlite"))'

    # Render READEME.md using rmarkdown
    - name: render weather report
      run: Rscript -e 'rmarkdown::render("rpa-write-rmd-file.Rmd")'

    - name: commit rendered README
      run: |
        git add rpa-write-rmd-file.Rmd rpa-write-rmd-file.html
        git commit -m "Re-compile rpa-write-rmd-file.Rmd" || echo "No changes to commit"
        git push origin gh-pages || echo "No changes to commit"
        

